### PR TITLE
Add Polish

### PR DESCRIPTION
**Pull request by tzjan**
Please check my changes to add the polish language, Thx

### CODE REVIEW

**Comment by tbrowder** [comment]
@tzjan, thanks!  I think you need to change file t/003-have-full-names.t to have 190 tests.

Also, please add a new test file named t/007-pl-lang-class.t similar to the other lang tests as appropriate. 

And don't forget to give yourself credit in the README.md!

**Comment by tbrowder** [comment]
I didn’t mean to close the PR, reopening.

**Comment by tzjan** [comment]
The tests seems to be fixed now.
The particular pl test is generated with the provided test generator.
Please review. Thx

**Comment by tbrowder** [comment]
Thanks very much!

**Pull request merged**
